apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: workflow-provisioner
  template:
    metadata:
      labels:
        app: workflow-provisioner
    spec:
      serviceAccountName: workflow-provisioner-admin
      imagePullSecrets:
        - name: imla-registry
      containers:
        - name: workflow-provisioner
          image: harbor.gx4ki.imla.hs-offenburg.de/gx4ki/workflow-provisioner@latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: database
              mountPath: /opt/database
          envFrom:
            - configMapRef:
                name: workflow-provisioner-env
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: workflow-provisioner
