apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: workflow-provisioner-admin
rules:
  - apiGroups:
      - ""
      - apps
      - rbac.authorization.k8s.io
      - networking.k8s.io
    resources:
      - namespaces
      - deployments
      - configmaps
      - secrets
      - services
      - ingresses
      - rolebindings
      - roles
      - serviceaccounts
      - persistentvolumeclaims
    verbs:
      - create
      - get
      - delete
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - delete
      - get
      - create
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workflow-provisioner-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workflow-provisioner-admin
subjects:
  - kind: ServiceAccount
    name: workflow-provisioner-admin
    namespace: workflow-provisioner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflow-api
rules:
  # - nonResourceURLs: ["/healthz", "/readyz", "/livez"]
  #   verbs: ["get"]
  - apiGroups:
      - ""
    resources: ["pods"]
    verbs: ["get", "delete", "create", "list", watch]
  - apiGroups:
      - ""
    resources: ["pods/portforward"]
    verbs: ["get", "create"]
  - apiGroups:
      - ""
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups:
      - ""
    resources: ["configmaps"]
    verbs: ["create", "delete"]
  - apiGroups:
      - ""
    resources: ["events"]
    verbs: ["watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workflow-api-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workflow-api
subjects:
  - kind: ServiceAccount
    name: workflow-provisioner-admin
    namespace: workflow-provisioner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-provisioner-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: workflow-provisioner-token
  annotations:
    kubernetes.io/service-account.name: workflow-provisioner-admin
type: kubernetes.io/service-account-token
