apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: workflow-provisioner-admin
rules:
  - apiGroups:
      - ""
      - apps
      - rbac.authorization.k8s.io
    resources:
      - namespaces
      - depoyments
      - configmaps
      - secret
      - services
      - ingress
      - rolebindings
      - roles
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workflow-provisioner-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workflow-provisioner-admin
subjects:
  - kind: ServiceAccount
    name: workflow-provisioner-admin
    namespace: gx4ki-workflow-provisioner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-provisioner-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: workflow-provisioner-token
  annotations:
    kubernetes.io/service-account.name: workflow-provisioner-admin
type: kubernetes.io/service-account-token
