apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-api
spec:
  selector:
    matchLabels:
      app: workflow-api
  template:
    metadata:
      labels:
        app: workflow-api
    spec:
      imagePullSecrets:
        - name: imla-registry
      serviceAccountName: workflow-api-service-account
      volumes:
        - name: workflow-api-config
          secret:
            secretName: workflow-api-config
        - name: demo-assets
          configMap:
            name: demo-assets
      containers:
        - name: workflow-api
          image: harbor.gx4ki.imla.hs-offenburg.de/gx4ki/workflow-api:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: workflow-api-env
          volumeMounts:
            - mountPath: /opt/config/
              name: workflow-api-config
              readOnly: true
            - name: demo-assets
              mountPath: /opt/config/assets
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-api
spec:
  type: ClusterIP
  selector:
    app: workflow-api
  ports:
    - port: 8080
      targetPort: 8080
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: workflow-api-ingress
#   labels:
#     name: workflow-api-ingress
# spec:
#   rules:
#   - host: k8s.local
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: workflow-api
#             port:
#               number: 80

