apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-api-role
rules:
  # - nonResourceURLs: ["/healthz", "/readyz", "/livez"]
  #   verbs: ["get"]
  - apiGroups:
      - ""
    resources: ["pods"]
    verbs: ["get", "delete", "create", "list", watch]
  - apiGroups:
      - ""
    resources: ["pods/portforward"]
    verbs: ["get", "create"]
  - apiGroups:
      - ""
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups:
      - ""
    resources:
      - configmaps
      - persistentvolumeclaims
    verbs:
      - create
      - delete
  - apiGroups:
      - ""
    resources: ["events"]
    verbs: ["watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-api-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-api-role
subjects:
  - kind: ServiceAccount
    name: workflow-api-service-account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-api-service-account
---
apiVersion: v1
kind: Secret
metadata:
  name: workflow-api-token
  annotations:
    kubernetes.io/service-account.name: workflow-api-service-account
type: kubernetes.io/service-account-token
