apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-assets
data:
  dummy.json: |
    {
      "service_id": "dummy",
      "inputs": [
          {
              "resource_name": "env",
              "type": 1,
              "description": "List of environment Variables for dummy-job Container"
          }
      ],
      "outputs": [
          {
              "resource_name": "result",
              "type": 2,
              "description": "dummy output file"
          }
      ],
      "workflow_resource": {
          "worker_image": "imlahso/dummy-job:latest",
          "worker_image_output_directory": "/output/",
          "worker_image_args": ["entrypoint.sh"],
          "worker_image_command": ["/bin/sh"],
          "gpu": false
      }
    }
