apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-assets
data:
  dummy.json: |
    {
      "service_id": "dummy",
      "inputs": [
          {
              "resource_name": "env",
              "type": 1,
              "description": "List of environment Variables for dummy-job Container"
          }
      ],
      "outputs": [
          {
              "resource_name": "result",
              "type": 2,
              "description": "dummy output file"
          }
      ],
      "workflow_resource": {
          "worker_image": "harbor.gx4ki.imla.hs-offenburg.de/gx4ki/dummy-job@sha256:4dc4743b414b84aebcbe1755f3172c40811868caafffbbdad31925642763637b",
          "worker_image_output_directory": "/output/",
          "worker_image_args": ["entrypoint.sh"],
          "worker_image_command": ["/bin/sh"],
          "gpu": false
      }
    }
  carla.json: |
    {
      "service_id": "carla",
      "inputs":
        [
          {
            "resource_name": "env",
            "type": 1,
            "description": "List of environment Variables for Carla Container"
          }
        ],
      "outputs":
        [
          {
            "resource_name": "rosbag.bag",
            "type": 2,
            "description": "Generated rosbag file from .env file"
          }
        ],
      "workflow_resource":
        {
          "worker_image": "harbor.gx4ki.imla.hs-offenburg.de/gx4ki/carla:test",
          "worker_image_output_directory": "/home/carla/rosbag",
          "worker_image_args": ["entrypoint.sh"],
          "worker_image_command": ["/bin/bash"],
          "gpu": true
        }
    }
