# generated by datamodel-codegen:
#   filename:  transfer-process-api.yaml
#   timestamp: 2023-05-16T13:30:41+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

# pylint: disable=no-name-in-module
from pydantic import BaseModel


class ApiErrorDetail(BaseModel):
    invalidValue: Optional[str] = None
    message: Optional[str] = None
    path: Optional[str] = None
    type: Optional[str] = None


class CriterionDto(BaseModel):
    operandLeft: Dict[str, Any]
    operandRight: Optional[Dict[str, Any]] = None
    operator: str


class DataAddress(BaseModel):
    properties: Optional[Dict[str, str]] = None


class DataAddressInformationDto(BaseModel):
    properties: Optional[Dict[str, str]] = None


class DataRequestDto(BaseModel):
    assetId: Optional[str] = None
    connectorId: Optional[str] = None
    contractId: Optional[str] = None
    id: Optional[str] = None


class IdResponseDto(BaseModel):
    createdAt: Optional[int] = None
    id: Optional[str] = None


class SortOrder(Enum):
    ASC = 'ASC'
    DESC = 'DESC'


class QuerySpecDto(BaseModel):
    filter: Optional[str] = None
    filterExpression: Optional[List[CriterionDto]] = None
    limit: Optional[int] = None
    offset: Optional[int] = None
    sortField: Optional[str] = None
    sortOrder: Optional[SortOrder] = None


class TransferProcessDto(BaseModel):
    createdAt: Optional[int] = None
    dataDestination: Optional[DataAddressInformationDto] = None
    dataRequest: Optional[DataRequestDto] = None
    errorDetail: Optional[str] = None
    id: Optional[str] = None
    state: Optional[str] = None
    stateTimestamp: Optional[int] = None
    type: Optional[str] = None
    updatedAt: Optional[int] = None


class TransferState(BaseModel):
    state: Optional[str] = None


class TransferType(BaseModel):
    contentType: Optional[str] = None
    isFinite: Optional[bool] = None


class TransferRequestDto(BaseModel):
    assetId: str
    connectorAddress: str
    connectorId: str
    contractId: str
    dataDestination: DataAddress
    id: Optional[str] = None
    managedResources: Optional[bool] = None
    properties: Optional[Dict[str, str]] = None
    protocol: str
    transferType: TransferType
